In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("dataset.csv")
df

,title,description,genres
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","Animation, Adventure, Family, Comedy"
1,Jumanji,Four teenagers in detention discover an old vi...,"Adventure, Comedy, Fantasy, Action, Family"
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"Romance, Comedy"
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","Comedy, Drama, Romance"
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"Comedy, Family"
...,...,...,...
95,Hate,Journalist Kavya Krishna loves tycoon Siddhart...,"Drama, Thriller"
96,Shopping,“WAGERL” takes a humorous look at the controve...,Documentary
97,Heidi Fleiss: Hollywood Madam,A documentary crew from the BBC arrives in L.A...,Documentary
98,City Hall,"Michelle Buteau talks going viral, raising twi...",Comedy
99,Bottle Rocket,Peter sends a bottle rocket into space and tel...,Comedy

In [ ]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer


df['genres_list'] = df['genres'].apply(lambda x: [g.strip() for g in x.split(",")])
mlb = MultiLabelBinarizer()
genre_one_hot = mlb.fit_transform(df['genres_list'])

print("All unique genres found:")
print(mlb.classes_)

genre_df = pd.DataFrame(genre_one_hot, columns=mlb.classes_)

df = pd.concat([df, genre_df], axis=1)

df.head()

All unique genres found:
['Action' 'Adventure' 'Animation' 'Comedy' 'Crime' 'Documentary' 'Drama'
 'Family' 'Fantasy' 'History' 'Horror' 'Music' 'Mystery' 'Romance'
 'Science Fiction' 'TV Movie' 'Thriller' 'War']

,title,description,genres,genres_list,Action,Adventure,Animation,Comedy,Crime,Documentary,...,Fantasy,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","Animation, Adventure, Family, Comedy","[Animation, Adventure, Family, Comedy]",0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Jumanji,Four teenagers in detention discover an old vi...,"Adventure, Comedy, Fantasy, Action, Family","[Adventure, Comedy, Fantasy, Action, Family]",1,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"Romance, Comedy","[Romance, Comedy]",0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","Comedy, Drama, Romance","[Comedy, Drama, Romance]",0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"Comedy, Family","[Comedy, Family]",0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0